query getAdminUsers($filter: GetAdminUsersFilterInput!) {
  adminUsers(filter: $filter) {
    id
    first_name
    last_name
    email
    createdAt
    status
  }
}

query adminDashboardStatistics {
  adminDash {
    total_number_of_users
    total_revenue
    total_number_of_physicians
    total_number_of_appointments
  }
}

query AdminPhysicianAppointment($filter: GetAppointmentInput!) {
  appointments(filter: $filter) {
    id
    patient {
      first_name
      last_name
      email
      patientProfile {
        profileImage
      }
    }
    doctor {
      first_name
      last_name
    }
    appointmentTimeSlots {
      startTime
      endTime
      selected
    }
    appointmentSchedule {
      startTime
      endTime
    }
    appointmentDateTime {
      startTime
      endTime
    }
    charges
    status
    serviceType {
      name
    }
  }
}

query getPatients($filter: GetPatientsInput!) {
  getPatients(filter: $filter) {
    id
    first_name
    last_name
    email
    contact_number
    createdAt
    streetAddress
    zip_code
    state {
      state_name
    }
    city {
      city_name
    }
    country {
      country_name
    }
  }
}

# Pay Physician From Admin
mutation physicianPaymentByAdmin($paymeninput: PaymentInput!) {
  payment(paymentInput: $paymeninput) {
    id
    transactionId
    appointmentId
    cardId
    amountReceived
    status
    doctor_percentage
    payment_status
    createdAt
  }
}

# Admin General Settings
mutation createAdminSettings(
  $createAdminSettingInput: [CreateAdminSettingInput!]!
) {
  createAdminSetting(createAdminSettingInput: $createAdminSettingInput) {
    id
    key
    value
  }
}

# query adminUser($filter: GetAdminUsersFilterInput!) {
#   adminUser(filter: $filter) {
#     id
#     first_name
#     last_name
#     email
#     password
#     contact_number
#     adminProfilePicture{
#       profile_picture
#     }
#   }
# }

query adminUser($id: Int!) {
  adminUser(id: $id) {
    id
    first_name
    last_name
    email
    contact_number

    adminProfilePicture {
      profile_picture
    }
  }
}

# remove admin user
mutation removeAdminUser($id: Int!) {
  removeUser(id: $id) {
    id
  }
}
