query getAdminUsers($filter: GetAdminUsersFilterInput!) {
  adminUsers(filter: $filter) {
    id
    first_name
    last_name
    email
    createdAt
    status
  }
}

query adminDashboardStatistics {
  adminDash {
    total_number_of_users
    total_revenue
    total_number_of_physicians
    total_number_of_appointments
  }
}

query AdminPhysicianAppointment($filter: GetAppointmentInput!) {
  appointments(filter: $filter) {
    id
    patient {
      first_name
      last_name
    }
    appointmentTimeSlots {
      startTime
      endTime
      selected
    }
    appointmentSchedule {
      startTime
      endTime
    }
    charges
    status
  serviceType {
    name
  }
  }
}

query getPatients($filter: GetPatientsInput!) {
  getPatients(filter: $filter) {
    id
    first_name
    last_name
    email
    gender
    date_of_birth
    contact_number
    streetAddress
    country_id
    deleted
    state_id
    city_id
    zip_code
    password
    status
    role
    doctorId
    createdAt
  }
}
