query getAllChatChannels {
  getAllChatChannels {
    id
    channelName
    doctorId
    patientId
    isAdminChat
    createdAt
    receiverDetail {
      first_name
      last_name
      role
      email
     adminProfilePicture {
        profile_picture
      }
      doctorProfile {
        profile_image
      }
      patientProfile {
        profileImage
      }
    }
    participants {
      id
      channelId
      participantId
      channel {
        id
        channelName
        doctorId
        patientId
        isAdminChat
      }
      userDetails {
        id
        first_name
        last_name
        email
        role
        chatChannel {
          channelName
          doctorId
          patientId
          isAdminChat
        }
        doctorProfile {
          profile_image
        }
        patientProfile {
          profileImage
        }
      }
    }
  }
}

query getChannelMessages($channelId: Int!) {
  getChannelMessages(channelId: $channelId) {
    id
    channelId
    senderId
    message
    messageType
    createdAt
    sender {
      first_name
      last_name
      doctorProfile {
        profile_image
      }
      patientProfile {
        profileImage
      }
    }
  }
}

query checkEmailAvailability($emailAvailableInput: EmailAvailableInput!) {
  checkEmailAvailability(emailAvailableInput: $emailAvailableInput) {
    isEmailAvailable
  }
}
