query getAllChatChannels {
  getAllChatChannels {
    id
    channelName
    doctorId
    patientId
    isAdminChat
    createdAt
    participants {
      id
      channelId
      participantId
      channel {
        id
        channelName
        doctorId
        patientId
        isAdminChat
      }
      userDetails {
        id
        first_name
        last_name
        doctorProfile {
          profile_image
        }
        patientProfile {
          profileImage
        }
      }
    }
    doctor {
      id
      first_name
      last_name
      doctorProfile {
        profile_image
      }
    }
  }
}
