query countries {
  countries {
    id
    country_name
  }
}

query getStatesByCountry($input: Int!) {
  getStatesByCountry(country_id: $input) {
    id
    country_id
    state_name
  }
}

query getCitiesByState($input: Int!) {
  getCitiesByState(state_id: $input) {
    id
    state_id
    city_name
  }
}

# GET PATIENT HEALTH HISTORY
query patientHealthHistory($input: Int!) {
  patientHealthHistory(id: $input) {
    id
    history
  }
}

# GET ALL CARDS
query getAllCards($userId: Int!) {
  getAllCards(user_id: $userId) {
    id
    user_id
    card_id
    card_type
    card_digits
    is_default
    exp_month
    exp_year
  }
}

# GET CARD QUERY
query getCard($id: Int!) {
  getCard(id: $id) {
    id
    user_id
    card_id
    card_type
    card_digits
    is_default
  }
}

# GET USER

query getUser($input: Int!) {
  user(id: $input) {
    id
    first_name
    last_name
    gender
    date_of_birth
    contact_number
    email
    country_id
    city_id
    state_id
    password
    zip_code
    streetAddress
    patientProfile {
      maritalStatus
      profileImage
      children
      occupation
      occupationalExposure
      pets
      petsAnswer
      exposureDuration
      userId
    }
  }
}

# GET ALL DOCTORS
query doctorProfiles {
  doctorProfiles {
    id
    doctor_id
    year_of_experience
    specialization
    condition_treated
    educational_background
    professional_experience
    language
    about_me
    user {
      id
      first_name
      last_name
      email
      gender
    }
  }
}

# GET SINGLE DOCTOR PROFILE

# query doctorProfile($doctor_id: Int!) {
#   doctorProfile(doctor_id: $doctor_id) {
#     id
#     doctor_id
#     year_of_experience
#     specialization
#     condition_treated
#     educational_background
#     professional_experience
#     language
#     about_me
#     profile_image
#     user {
#       id
#       first_name
#       last_name
#       email
#       gender
#       date_of_birth
#       country_id
#       state_id
#       city_id
#       zip_code
#       password
#       status
#       role
#       doctorSchedules {
#         id
#         doctorId
#         day
#         startTime
#         endTime
#         createdAt
#         updatedAt
#       }
#     }
#   }
# }

query doctorProfile($doctor_id: Int!) {
  doctorProfile(doctor_id: $doctor_id) {
    id
    doctor_id
    year_of_experience
    specialization
    condition_treated
    educational_background
    professional_experience
    language
    about_me
    profile_image
    user {
      id
      first_name
      last_name
      email
      gender
      country_id
      state_id
      city_id
      zip_code
      password
      status
      role
      doctorSchedules {
        id
        doctorId
        day
        startTime
        endTime
        createdAt
        updatedAt
      }
    }
  }
}

# get all appointments
query getAllRequestedAppointments($filter: GetAppointmentInput!) {
  appointments(filter: $filter) {
    id
    patientId
    doctorId
    serviceId
    requestedDate
    status
    charges
    patient {
      first_name
      last_name
    }
    serviceType {
      name
      price
    }
    doctor {
      first_name
      last_name
    }
    appointmentTimeSlots {
      id
      startTime
      endTime
      selected
    }
    transaction {
      createdAt
      amountReceived
    }
  }
}
# query getAllRequestedAppointments($filter: GetAppointmentInput!) {
#   appointments(filter: $filter) {
#     id
#     patientId
#     doctorId
#     serviceId
#     requestedDate
#     status
#     patient{
#       first_name
#       last_name
#     }
#     serviceType{
#       name
#     }
#     doctor{
#       first_name
#     }
#   }
# }
# GET DOCTOR PROFILE DETAILS
query doctorProfileDetails($input: Int!) {
  user(id: $input) {
    id
    first_name
    last_name
    email
    streetAddress
    country_id
    state_id
    city_id
    zip_code

    doctorProfile {
      id
      year_of_experience
      specialization
      condition_treated
      educational_background
      professional_experience
      language
      about_me
      profile_image
    }
    doctorSchedules {
      day
      startTime
      endTime
    }
  }
}

#GET APPOINMENT SERVICE TYPES
query getAllAppointmentServiceTypes {
  appointmentServiceTypes {
    id
    name
    price
  }
}

#GET DOCTOR SCHEDULES
query doctorSchedules($doctorId: Int!) {
  doctorSchedules(doctorId: $doctorId) {
    id
    doctorId
    day
    startTime
    endTime
  }
}

#GET DOCTOR QUESTIONAIRES
query doctorQuestionnaire($doctorId: Int!) {
  doctorQuestionnaire(doctorId: $doctorId) {
    id
    doctorId
    questionnaire
  }
}

#GET APPOINMENT BY ID
query getAppointmentById($id: Int!) {
  appointment(id: $id) {
    id
    status
    scheduleId
    doctorId
    patientId
    requestedDate
    reportUrl
    doctor {
      id
      first_name
      last_name
    }
    patient {
      id
      first_name
      last_name
    }
    appointmentTimeSlots {
      id
      startTime
      endTime
      selected
    }
    appointmentSchedule {
      id
      day
      doctorId
      startTime
      endTime
    }
    serviceType {
      id
      name
      price
    }
    transaction {
      createdAt
    }
    appointmentHealthHistory {
      history
    }
  }
}

# GET ALL TRANSACTIONS
query getAllTransactions {
  transactions {
    id
    transactionId
    appointmentId
    amountReceived
    status
    createdAt
    appointment {
      requestedDate
      reportUrl
      doctor {
        first_name
        last_name
      }
      patient {
        first_name
        last_name
      }
      serviceType {
        id
        name
      }
      appointmentTimeSlots {
        selected
        startTime
        endTime
      }
    }
  }
}

# Get Doctor Schedules
query schedule($doctorId: Int!) {
  doctorSchedules(doctorId: $doctorId) {
    id
    startTime
    endTime
    day
  }
}

# query GetAllAppointment($id: Int!) {
#   appointment(id: $id) {
#     status
#     appointmentTimeSlots {
#       id
#       startTime
#       endTime
#       selected
#     }
#   }
# }

#VIEW SUGGESTED TIME SLOTS

query ViewSuggestedTimeSlots($id: Int!) {
  appointment(id: $id) {
    id
    patientId
    doctorId
    charges
    serviceId
    scheduleId
    requestedDate
    reportUrl
    status
    createdAt
    appointmentTimeSlots {
      id
      startTime
      endTime
      selected
    }
    serviceType {
      name
      price
    }
    doctor {
      first_name
      last_name
    }
  }
}

#GET APPOINTMENT FOR REMINDER
query getAppointmentsReminderBanner {
  appointmentsReminderBanner {
    id
    patient {
      first_name
      last_name
    }
    doctor {
      first_name
      last_name
    }
    appointmentTimeSlots {
      startTime
      endTime
      selected
    }
  }
}

#GET COUNTRY BY ID
query getCountryById($id: Int!) {
  country(id: $id) {
    id
    country_name
    country_short_name
    country_phone_code
  }
}

#GET CITY BY ID
query getCityById($id: Int!) {
  city(id: $id) {
    id
    state_id
    city_name
  }
}

#GET APPOINMENT BY ID
query getAppointmentReportUrlById($id: Int!) {
  appointment(id: $id) {
    id
    doctorId
    patientId
    reportUrl
  }
}
