query countries {
  countries {
    id
    country_name
  }
}

query getStatesByCountry($input: Int!) {
  getStatesByCountry(country_id: $input) {
    id
    country_id
    state_name
  }
}

query getCitiesByState($input: Int!) {
  getCitiesByState(state_id: $input) {
    id
    state_id
    city_name
  }
}

# GET PATIENT HEALTH HISTORY
query patientHealthHistory($input: Int!) {
  patientHealthHistory(id: $input) {
    id
    history
  }
}

# GET ALL CARDS
query getAllCards($userId: Int!) {
  getAllCards(user_id: $userId) {
    id
    user_id
    card_id
    card_type
    card_digits
    is_default
    exp_month
    exp_year
  }
}

# GET CARD QUERY
query getCard($id: Int!) {
  getCard(id: $id) {
    id
    user_id
    card_id
    card_type
    card_digits
    is_default
  }
}

# GET USER

query getUser($input: Int!) {
  user(id: $input) {
    id
    first_name
    last_name
    gender
    date_of_birth
    contact_number
    email
    country_id
    city_id
    state_id
    zip_code
    streetAddress
    status
    country {
      country_name
    }
    state {
      state_name
    }
    city {
      city_name
    }
    patientProfile {
      maritalStatus
      profileImage
      children
      haveChildren
      occupation
      occupationalExposure
      pets
      petsAnswer
      exposureDuration
      userId
    }
    doctorProfile {
      id
      doctor_id
      year_of_experience
      specialization
      condition_treated
      educational_background
      professional_experience
      language
      about_me
      profile_image
    }
  }
}

# GET ALL DOCTORS
query doctorProfiles {
  doctorProfiles {
    id
    doctor_id
    year_of_experience
    specialization
    condition_treated
    educational_background
    professional_experience
    language
    about_me
    profile_image
    user {
      id
      first_name
      last_name
      email
      gender
      doctorQuestionnaire {
        id
        doctorId
        questionnaire
        languageId
      }
    }
  }
}

# GET SINGLE DOCTOR PROFILE

# query doctorProfile($doctor_id: Int!) {
#   doctorProfile(doctor_id: $doctor_id) {
#     id
#     doctor_id
#     year_of_experience
#     specialization
#     condition_treated
#     educational_background
#     professional_experience
#     language
#     about_me
#     profile_image
#     user {
#       id
#       first_name
#       last_name
#       email
#       gender
#       date_of_birth
#       country_id
#       state_id
#       city_id
#       zip_code
#       password
#       status
#       role
#       doctorSchedules {
#         id
#         doctorId
#         day
#         startTime
#         endTime
#         createdAt
#         updatedAt
#       }
#     }
#   }
# }

query doctorProfile($doctor_id: Int!) {
  doctorProfile(doctor_id: $doctor_id) {
    id
    doctor_id
    year_of_experience
    specialization
    condition_treated
    educational_background
    professional_experience
    awards_honors_recognition
    certification_and_licensure
    language
    about_me
    profile_image
    user {
      id
      first_name
      last_name
      email
      gender
      streetAddress
      country_id
      state_id
      city_id
      country {
        country_name
      }
      state {
        state_name
      }
      city {
        city_name
      }
      zip_code
      password
      status
      role
      contact_number
      doctorSchedules {
        id
        doctorId
        day
        startTime
        endTime
        createdAt
        updatedAt
      }
    }
  }
}

# get all appointments
query getAllRequestedAppointments(
  $filter: GetAppointmentInput!
  $pagination: PaginationParams
  $sorting: SortingParams
) {
  appointments(filter: $filter, pagination: $pagination, sorting: $sorting) {
    items {
      id
      patientId
      doctorId
      serviceId
      requestedDate
      reportUrl
      createdAt
      status
      charges
      patient {
        first_name
        last_name
      }
      serviceType {
        name
        price
      }
      doctor {
        first_name
        last_name
        doctorProfile {
          id
          doctor_id
          year_of_experience
          specialization
          condition_treated
          educational_background
          professional_experience
          language
          about_me
          profile_image
          user {
            doctorId
            id
            first_name
            last_name
            email
            gender
            country_id
            state_id
            city_id
            zip_code
            password
            status
            role
            doctorSchedules {
              id
              doctorId
              day
              startTime
              endTime
              createdAt
              updatedAt
            }
          }
        }
      }
      appointmentTimeSlots {
        id
        startTime
        endTime
        selected
      }
      transaction {
        createdAt
        status
        amountReceived
      }
      appointmentSchedule {
        startTime
        endTime
      }
      appointmentDateTime {
        startTime
        endTime
      }
    }
    meta {
      totalPages
      currentPage
    }
  }
}

# query getAllRequestedAppointments($filter: GetAppointmentInput!) {
#   appointments(filter: $filter) {
#     id
#     patientId
#     doctorId
#     serviceId
#     requestedDate
#     status
#     patient{
#       first_name
#       last_name
#     }
#     serviceType{
#       name
#     }
#     doctor{
#       first_name
#     }
#   }
# }
# GET DOCTOR PROFILE DETAILS
query doctorProfileDetails($input: Int!) {
  user(id: $input) {
    id
    first_name
    last_name
    email
    streetAddress
    country_id
    state_id
    city_id
    zip_code

    doctorProfile {
      id
      year_of_experience
      specialization
      condition_treated
      educational_background
      professional_experience
      language
      about_me
      profile_image
    }
    doctorSchedules {
      day
      startTime
      endTime
    }
  }
}

#GET APPOINTMENT SERVICE TYPES
query getAllAppointmentServiceTypes {
  appointmentServiceTypes {
    id
    name
    price
  }
}

#GET DOCTOR SCHEDULES
query doctorSchedules($doctorId: Int!) {
  doctorSchedules(doctorId: $doctorId) {
    id
    doctorId
    day
    startTime
    endTime
    createdAt
    updatedAt
  }
}

#GET DOCTOR QUESTIONAIRES
query doctorQuestionnaire($doctorId: Int!, $languageId: Int!) {
  doctorQuestionnaire(doctorId: $doctorId, languageId: $languageId) {
    id
    doctorId
    questionnaire
    languageId
  }
}

#GET APPOINTMENT BY ID
query getAppointmentById($id: Int!) {
  appointment(id: $id) {
    id
    status
    scheduleId
    doctorId
    patientId
    requestedDate
    reportUrl
    questionnaire
    doctor {
      id
      first_name
      last_name
      doctorQuestionnaire {
        questionnaire
        languageId
      }
    }
    patient {
      id
      first_name
      last_name
      patientProfile {
        profileImage
      }
      patientHealthHistory {
        history
        # doctor
        # doctor_id
      }
    }
    appointmentTimeSlots {
      id
      startTime
      endTime
      selected
    }
    appointmentDateTime {
      startTime
      endTime
    }
    serviceType {
      id
      name
      price
    }
    transaction {
      createdAt
      status
      amountReceived
    }
    createdAt
    charges
    appointmentHealthHistory {
      history
    }

    currentAppointmentNote {
      appointment {
        id
        doctor {
          id
          first_name
          last_name
        }
      }
      createdAt
      id
      subjective
      objective
      assessment
      plan
      note
      isPublished
    }
    notesHistory {
      appointment {
        id
        doctor {
          id
          first_name
          last_name
        }
      }
      createdAt
      id
      subjective
      objective
      assessment
      plan
      note
      isPublished
    }
    # currentAppointmentNote {
    #   id
    #   subjective
    #   objective
    #   assessment
    #   plan
    #   note
    #   isPublished
    # }
    # notesHistory {
    #   id
    #   subjective
    #   objective
    #   assessment
    #   plan
    #   note
    #   isPublished
    # }
  }
}

# GET ALL TRANSACTIONS
query getAllTransactions(
  $pagination: PaginationParams
  $sorting: SortingParams
) {
  transactions(pagination: $pagination, sorting: $sorting) {
    items {
      id
      transactionId
      appointmentId
      amountReceived
      status
      createdAt
      appointment {
        requestedDate
        reportUrl
        doctor {
          first_name
          last_name
        }
        patient {
          first_name
          last_name
        }
        serviceType {
          id
          name
        }
        appointmentTimeSlots {
          selected
          startTime
          endTime
        }
      }
    }
    meta {
      totalPages
      currentPage
    }
  }
}

# Get Doctor Schedules
query schedule($doctorId: Int!) {
  doctorSchedules(doctorId: $doctorId) {
    id
    startTime
    endTime
    day
  }
}

# query GetAllAppointment($id: Int!) {
#   appointment(id: $id) {
#     status
#     appointmentTimeSlots {
#       id
#       startTime
#       endTime
#       selected
#     }
#   }
# }

#VIEW SUGGESTED TIME SLOTS

query ViewSuggestedTimeSlots($id: Int!) {
  appointment(id: $id) {
    id
    patientId
    doctorId
    charges
    serviceId
    scheduleId
    requestedDate
    reportUrl
    status
    createdAt
    appointmentTimeSlots {
      id
      startTime
      endTime
      selected
    }
    serviceType {
      name
      price
    }
    doctor {
      first_name
      last_name
    }
    transaction {
      status
      amountReceived
    }
  }
}

#GET APPOINTMENT FOR REMINDER
query getAppointmentsReminderBanner {
  appointmentsReminderBanner {
    id
    patient {
      first_name
      last_name
    }
    doctor {
      first_name
      last_name
    }
    appointmentTimeSlots {
      startTime
      endTime
      selected
    }
  }
}

#GET COUNTRY BY ID
query getCountryById($id: Int!) {
  country(id: $id) {
    id
    country_name
    country_short_name
    country_phone_code
  }
}

#GET CITY BY ID
query getCityById($id: Int!) {
  city(id: $id) {
    id
    state_id
    city_name
  }
}

#GET APPOINTMENT BY ID
query getAppointmentReportUrlById($id: Int!) {
  appointment(id: $id) {
    id
    doctorId
    patientId
    reportUrl
  }
}

query getDoctorEarnings($filter: GetTransectionInput!, $id: Int!) {
  getDoctorEarnings(filter: $filter, id: $id) {
    total_number_of_consultation
    total_number_of_second_opinions
    total_number_of_patients
    total_earnings_from_consultation
    total_earnings_from_second_opinions
    total_earnings
  }
}

# get staff listing
query getAllStaffByDoctor(
  $filter: GetStaffFilter!
  $pagination: PaginationParams
  $sorting: SortingParams
) {
  staff(filter: $filter, pagination: $pagination, sorting: $sorting) {
    items {
      id
      role
      email
      first_name
      last_name
      contact_number
      doctorId
      createdAt
      status
    }
    meta {
      totalPages
      currentPage
    }
  }
}

#GET APPOINTMENT BY ID
query getStaffDetailsUrlById($id: Int!) {
  staffDetail(id: $id) {
    id
    first_name
    last_name
    status
    email
    contact_number
    createdAt
  }
}

# query getAdminUsers(
#   $filter: GetAdminUsersFilterInput!
#   $pagination: PaginationParams
#   $sorting: SortingParams
# ) {
#   adminUsers(filter: $filter, pagination: $pagination, sorting: $sorting) {
#     items {
#       id
#       first_name
#       last_name
#       email
#       createdAt
#       status
#     }
#     meta {
#       totalPages
#       currentPage
#     }
#   }
# }

query getAdminUserById($id: Int!) {
  user(id: $id) {
    id
    first_name
    last_name
    email
    createdAt
    status
  }
}

query getAppointmentNotesById($id: Int!) {
  appointment(id: $id) {
    doctor {
      id
      first_name
      last_name
    }

    currentAppointmentNote {
      appointment {
        id
        doctor {
          id
          first_name
          last_name
        }
      }
      createdAt
      id
      subjective
      objective
      assessment
      plan
      note
      isPublished
    }
    notesHistory {
      appointment {
        id
        doctor {
          id
          first_name
          last_name
        }
      }
      createdAt
      id
      subjective
      objective
      assessment
      plan
      note
      isPublished
    }
    # currentAppointmentNote {
    #   id
    #   appointmentId
    #   subjective
    #   objective
    #   assessment
    #   plan
    #   note
    #   isPublished
    # }
    # notesHistory {
    #   id
    #   appointmentId
    #   subjective
    #   objective
    #   assessment
    #   plan
    #   note
    #   isPublished
    # }
  }
}
