query userEmailPreferences {
  userEmailPreferences {
    appointment_accepted_by_doctor
    appointment_slot_suggested_by_doctor
    appointment_rescheduled_by_doctor
    appointment_reminder
    admin_appointment_create_update
    new_message_received
  }
}

query patientLastQuestionnaire($doctorId: Int!, $patientId: Int!) {
  patientLastQuestionnaire(doctorId: $doctorId, patientId: $patientId) {
    history
  }
}

query getDoctorNotesByAppId($id: Int!) {
  appointment(id: $id) {
    id
    patientId
    status
    doctorNote {
      subjective
      objective
      assessment
      plan
      note
      isPublished
    }
  }
}
