trigger:
  batch: true
  branches:
    include:
      - master
      - development

  paths:
    include:
      - "*"
    exclude:
      - "README.md"

pr:
  branches:
    include:
      - master
      - development

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: buildPackage
    displayName: "Build and Package"
    jobs:
      - job: build
        displayName: "Build and Test"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: "Install Node.js"

          - script: npm install
            displayName: "Install Dependencies"

          - script: npm run lint
            displayName: "Code Analysis"

          - task: SonarQubePrepare@5
            displayName: "Prepare SonarQube Analysis"
            condition: eq(variables['Build.SourceBranchName'], 'master')
            inputs:
              SonarQube: "cc-sonarqube"
              scannerMode: "CLI"
              configMode: "manual"
              cliProjectKey: "medicus"
              cliProjectName: "Medicus FrontEnd"
              cliSources: "."
              extraProperties: |
                sonar.sourceEncoding=UTF-8
                sonar.scm.provider=git

          - task: SonarQubeAnalyze@5
            condition: eq(variables['Build.SourceBranchName'], 'master')
            displayName: "Run SonarQube Analysis"

          - task: SonarQubePublish@5
            condition: eq(variables['Build.SourceBranchName'], 'master')
            displayName: "Publish SonarQube Analysis"
            inputs:
              pollingTimeoutSec: "300"

          - script: npm run build
            displayName: "Build Package"

      - job: package
        displayName: "Package Artifact"
        dependsOn: build
        condition: and(succeeded(), or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.SourceBranchName'], 'development')))
        steps:
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
              ArtifactName: "medicus"
              publishLocation: "Container"
