mutation createUser($input: CreateUserInput!) {
  createUser(createUserInput: $input) {
    id
    email
  }
}

mutation CreatePatientHealthHistory($input: CreatePatientHealthHistoryInput!) {
  createPatientHealthHistory(createPatientHealthHistoryInput: $input) {
    id
  }
}

mutation UpdatePatientHealthHistory($input: UpdatePatientHealthHistoryInput!) {
  updatePatientHealthHistory(updatePatientHealthHistoryInput: $input) {
    id
  }
}

mutation userVerifyEmail($input: String!) {
  userVerifyEmail(token: $input) {
    id
  }
}

mutation login($input: LoginUserInput!) {
  login(loginUserInput: $input) {
    access_token
    user {
      id
      email
      role
    }
  }
}

mutation UserForgotPassword($input: String!) {
  UserForgotPassword(email: $input) {
    id
  }
}

mutation UserResetPassword($input: ResetPasswordInput!) {
  UserResetPassword(resetPasswordInput: $input) {
    id
  }
}

# SET ADMIN PHYSICIAN PASSWORD
mutation setDoctorPassword($setPasswordInput: ResetPasswordInput!) {
  setDoctorPassword(setPasswordInput: $setPasswordInput) {
    id
  }
}

# CREATE CARD MUTATION
mutation createCard($input: CreatePaymentInput!) {
  createCard(createPaymentInput: $input) {
    id
    user_id
    card_id
    card_type
    card_digits
    is_default
    exp_month
    exp_year
  }
}

# REMOVE CARD MUTATION
mutation removeCard($input: Int!) {
  removeCard(id: $input) {
    id
    user_id
    card_id
    card_type
    card_digits
    is_default
  }
}

# DEFAULT CARD SET
mutation DefaultCard($input: Int!) {
  setAsDefaultCard(id: $input) {
    id
    user_id
    card_id
    card_type
    card_digits
    is_default
  }
}

# UPDATE USER MUTATION
mutation updateUserProfile($id: Int!, $updateUserInput: UpdateUserInput!) {
  updateUser(id: $id, updateUserInput: $updateUserInput) {
    first_name
    last_name
    email
    gender
    date_of_birth
    country_id
    contact_number
    city_id
    password
    state_id
    role
    zip_code
    streetAddress
  }
}

# CREATE DOCTOR MUTATION
mutation createDoctor($createDoctorInput: CreateDoctorInput!) {
  createDoctor(createDoctorInput: $createDoctorInput) {
    first_name
    last_name
    email
    streetAddress
    country_id
    state_id
    city_id
    zip_code
    id
  }
}

# DOCTOR UPDATE MUTATION
mutation updateDoctorProfile(
  $updateDoctorProfileInput: UpdateDoctorProfileInput!
) {
  updateDoctorProfile(updateDoctorProfileInput: $updateDoctorProfileInput) {
    id
    doctor_id
    year_of_experience
    specialization
    condition_treated
    educational_background
    professional_experience
    language
    about_me
    profile_image
    user {
      id
      first_name
      last_name
      email
      gender
      streetAddress
      country_id
      state_id
      city_id
      zip_code
      password
      status
      role
    }
  }
}

#ENABLE OR DISABLE DOCTOR
mutation enableOrDisableDoctor($id: Int!) {
  enableOrDisableDoctor(id: $id) {
    id
    status
  }
}

#CREATE APPOINMENT
mutation createAppointment($createAppointment: CreateAppointmentInput!) {
  createAppointment(createAppointmentInput: $createAppointment) {
    patientId
    doctorId
    serviceId
    requestedDate
    scheduleId
    reportUrl
  }
}

#CANCEL APPOINTMENT BY APPOINMENT
mutation cancelAppointmentByPatient($id: Int!) {
  cancelAppointmentByPatient(id: $id) {
    id
    patientId
    doctorId
    serviceId
    scheduleId
    requestedDate
    reportUrl
    status
    createdAt
  }
}
