mutation createUser($input: CreateUserInput!) {
  createUser(createUserInput: $input) {
    id
    email
  }
}

mutation CreatePatientHealthHistory($input: CreatePatientHealthHistoryInput!) {
  createPatientHealthHistory(createPatientHealthHistoryInput: $input) {
    id
  }
}

mutation userVerifyEmail($input: String!) {
  userVerifyEmail(token: $input) {
    id
  }
}

mutation login($input: LoginUserInput!) {
  login(loginUserInput: $input) {
    access_token
    user {
      id
      email
      role
    }
  }
}
